<?php
function fa_menu() {

    $items['learn/form-api'] = array(
        'title' => t('Form API'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('first_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );


    return $items;
}

function first_form(){
    $form=array();
    $form['name'] = array(
        '#type'	=> 'textfield',
        '#title' => t('Назва поля'),
        '#default_value' => t('Текст по замовчуванню '),
    );
    $form['settings'] = array(
        '#type' => 'radios',
        '#title' => t('Статус'),
        '#options' => array(0 => t('Статус 1'), 1 => t('Статус 2')),
        '#description' => t('Опис даного елемента.'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit'),
    );
    $form['#validate'][] = 'validate_name';

    return $form;
}

function validate_name($form, &$form_state) {
    if(!preg_match("'[A-Z]+[a-z]*$'", $form_state['values']['name']))
        form_set_error ("name", $form_state['values']['name'] . " <b>is not name.</b>");
}

